### ISSUE TITLE
Change Dyno types through the Heroku API

### ISSUE THREAD

**Issue by parveenq3** [TransitScreen/php-heroku-client#11]
We are currently using this API in the application and Its working to get dyno count and increase/decrease it.

But Is there any feature available in "php-heroku-client" API to get dyno type and change it using API?

Thanks

**Comment by ethanpooley** [comment]
First of all, I'm not sure why I didn't see this new issue until now. Sorry about that—I'll check my notification settings!

As to your question, it depends on what you mean by dyno "type". Heroku's docs use that word in a couple ways. Sometimes it refers to dyno size (e.g., `Standard-1X`, `Performance-M`, etc.). Other times it refers to the definitions in your application's `Procfile`, which are really about what the dyno "does", i.e. what process it runs. These are also called Formations in their docs. Assuming you are referring the dynos _size_ the answer is yes, you can do something like this:
```php
# Get the current dyno size.
$size = $heroku->get("apps/my-heroku-app-name/formation/my-formation-name")->size;

# If it's not what we want, change it.
if ($size !== 'Performance-M') {
    $heroku->patch(
        "apps/my-heroku-app-name/formation/my-formation-name",
        ['size' => 'Performance-M']
    );
}
```
If instead you are referring to the name of the formation, or to the process that a formation runs, then it would depend on what exactly you are trying to accomplish. At a glance it seems that while you can scale formations in both quantity and size, the processes those formations can run are limited by your Procfile. From the [Formation section](https://devcenter.heroku.com/articles/platform-api-reference#formation) of the docs:
>Available process type names and commands are defined by the process_types attribute for the slug currently released on an app.

So, possibly not.
