### ISSUE TITLE
PHP 8.0 - Incompatible Error

### ISSUE THREAD

**Issue by daz-williams** [TransitScreen/php-heroku-client#17]
`$ composer require php-heroku-client/php-heroku-client`

**[InvalidArgumentException]**
Package php-heroku-client/php-heroku-client has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

**Stack**
- Ubuntu 20
- Apache 2
- PHP 8
- Composer 2.0.8

**Comment by lukasjuhas** [comment]
#18

**Comment by SmarticoApps** [comment]
FYI: Running

    composer require --ignore-platform-reqs php-heroku-client/php-heroku-client

Appears to be a temporary workaround

**Comment by ethanpooley** [comment]
Thanks folks. I should be pushing a new version with official PHP 8 support and testing in a few days.

**Comment by ethanpooley** [comment]
Rolled this into #19.

**Comment by ethanpooley** [comment]
Released as v3.0.0

**Comment by lukasjuhas** [comment]
Thanks so much for sorting this so promptly. @ethanpooley
